name: Generate Keystore and Base64
on: workflow_dispatch

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Create Keystore
        run: |
          keytool -genkeypair -v \
          -keystore my-release-key.jks \	# a létrehozandó fájl neve. Ez is letölthető.
          -alias my-key-alias \		# például: key0 Fontos: Ezt a nevet pontosan ugyanígy kell majd beírnod a GitHub Secrets-be (ALIAS néven)
          -keyalg RSA \
          -keysize 2048 \
          -validity 100000 \		# érvényességi napok száma. Minimum 25 év legyen.
          -storepass paks2026 \		# például: dokinő		
          -keypass paks2026 \		# példásul: dokinő (ez is)
          -dname "CN=User, OU=AAPS, O=AAPS, L=Paks, S=Tolna, C=HU"

      - name: Convert to Base64
        run: |
          echo "Vágólapra másolható Base64 kód:"
          base64 -w 0 my-release-key.jks
          echo ""

      - name: Upload Keystore
        uses: actions/upload-artifact@v4
        with:
          name: my-keystore-file
          path: my-release-key.jks
